<?php
return [
    "liste_type_societe" => [
        ["value" => 1, "label" => "Particulier"],
        ["value" => 2, "label" => "Entreprise"],
    ],
    "liste_autorisations" => [
        ["value" => 1, "label" => "Autorisé", "badge" => "bg-vert", 'is_autorised' => true],
        ["value" => 2, "label" => "Non autorisé", "badge" => "bg-rouge", 'is_autorised' => false],
    ],
    "liste_mois" => [
        ["value" => "01", "label" => "Janvier"],
        ["value" => "02", "label" => "Février"],
        ["value" => "03", "label" => "Mars"],
        ["value" => "04", "label" => "Avril"],
        ["value" => "05", "label" => "Mai"],
        ["value" => "06", "label" => "Juin"],
        ["value" => "07", "label" => "Juillet"],
        ["value" => "08", "label" => "Août"],
        ["value" => "09", "label" => "Septembre"],
        ["value" => "10", "label" => "Octobre"],
        ["value" => "11", "label" => "Novembre"],
        ["value" => "12", "label" => "Décembre"],
    ],
    "liste_currencies" => [
        ["value" => 1, "label" => "Afghan Afghani", "abrv" => "AFN"],
        ["value" => 2, "label" => "Albanian Lek", "abrv" => "ALL"],
        ["value" => 3, "label" => "Algerian Dinar", "abrv" => "DZD"],
        ["value" => 4, "label" => "Angolan Kwanza", "abrv" => "AOA"],
        ["value" => 5, "label" => "Argentine Peso", "abrv" => "ARS"],
        ["value" => 6, "label" => "Armenian Dram", "abrv" => "AMD"],
        ["value" => 7, "label" => "Australian Dollar", "abrv" => "AUD"],
        ["value" => 8, "label" => "Azerbaijani Manat", "abrv" => "AZN"],
        ["value" => 9, "label" => "Bahraini Dinar", "abrv" => "BHD"],
        ["value" => 10, "label" => "Bangladeshi Taka", "abrv" => "BDT"],
        ["value" => 11, "label" => "Belarusian Ruble", "abrv" => "BYN"],
        ["value" => 12, "label" => "Belize Dollar", "abrv" => "BZD"],
        ["value" => 13, "label" => "Bermudian Dollar", "abrv" => "BMD"],
        ["value" => 14, "label" => "Bhutanese Ngultrum", "abrv" => "BTN"],
        ["value" => 15, "label" => "Bitcoin", "abrv" => "BTC"],
        ["value" => 16, "label" => "Bolivian Boliviano", "abrv" => "BOB"],
        ["value" => 17, "label" => "Botswana Pula", "abrv" => "BWP"],
        ["value" => 18, "label" => "Brazilian Real", "abrv" => "BRL"],
        ["value" => 19, "label" => "British Pound", "abrv" => "GBP"],
        ["value" => 20, "label" => "Brunei Dollar", "abrv" => "BND"],
        ["value" => 21, "label" => "Bulgarian Lev", "abrv" => "BGN"],
        ["value" => 22, "label" => "Burundian Franc", "abrv" => "BIF"],
        ["value" => 23, "label" => "Cambodian Riel", "abrv" => "KHR"],
        ["value" => 24, "label" => "Canadian Dollar", "abrv" => "CAD"],
        ["value" => 25, "label" => "Cape Verdean Escudo", "abrv" => "CVE"],
        ["value" => 26, "label" => "Cayman Islands Dollar", "abrv" => "KYD"],
        ["value" => 27, "label" => "Central African CFA Franc", "abrv" => "XAF"],
        ["value" => 28, "label" => "Chilean Peso", "abrv" => "CLP"],
        ["value" => 29, "label" => "Chinese Yuan", "abrv" => "CNY"],
        ["value" => 30, "label" => "Colombian Peso", "abrv" => "COP"],
        ["value" => 31, "label" => "Comorian Franc", "abrv" => "KMF"],
        ["value" => 32, "label" => "Congolese Franc", "abrv" => "CDF"],
        ["value" => 33, "label" => "Costa Rican Colón", "abrv" => "CRC"],
        ["value" => 34, "label" => "Croatian Kuna", "abrv" => "HRK"],
        ["value" => 35, "label" => "Cuban Peso", "abrv" => "CUP"],
        ["value" => 36, "label" => "Czech Koruna", "abrv" => "CZK"],
        ["value" => 37, "label" => "Danish Krone", "abrv" => "DKK"],
        ["value" => 38, "label" => "Djiboutian Franc", "abrv" => "DJF"],
        ["value" => 39, "label" => "Dominican Peso", "abrv" => "DOP"],
        ["value" => 40, "label" => "Egyptian Pound", "abrv" => "EGP"],
        ["value" => 41, "label" => "Ethiopian Birr", "abrv" => "ETB"],
        ["value" => 42, "label" => "Euro", "abrv" => "EUR"],
        ["value" => 43, "label" => "Fijian Dollar", "abrv" => "FJD"],
        ["value" => 44, "label" => "Gambian Dalasi", "abrv" => "GMD"],
        ["value" => 45, "label" => "Georgian Lari", "abrv" => "GEL"],
        ["value" => 46, "label" => "Ghanaian Cedi", "abrv" => "GHS"],
        ["value" => 47, "label" => "Guatemalan Quetzal", "abrv" => "GTQ"],
        ["value" => 48, "label" => "Guinean Franc", "abrv" => "GNF"],
        ["value" => 49, "label" => "Haitian Gourde", "abrv" => "HTG"],
        ["value" => 50, "label" => "Honduran Lempira", "abrv" => "HNL"],
        ["value" => 51, "label" => "Hong Kong Dollar", "abrv" => "HKD"],
        ["value" => 52, "label" => "Hungarian Forint", "abrv" => "HUF"],
        ["value" => 53, "label" => "Icelandic Króna", "abrv" => "ISK"],
        ["value" => 54, "label" => "Indian Rupee", "abrv" => "INR"],
        ["value" => 55, "label" => "Indonesian Rupiah", "abrv" => "valueR"],
        ["value" => 56, "label" => "Iranian Rial", "abrv" => "IRR"],
        ["value" => 57, "label" => "Iraqi Dinar", "abrv" => "IQD"],
        ["value" => 58, "label" => "Israeli New Shekel", "abrv" => "ILS"],
        ["value" => 59, "label" => "Jamaican Dollar", "abrv" => "JMD"],
        ["value" => 60, "label" => "Japanese Yen", "abrv" => "JPY"],
        ["value" => 61, "label" => "Jordanian Dinar", "abrv" => "JOD"],
        ["value" => 62, "label" => "Kazakhstani Tenge", "abrv" => "KZT"],
        ["value" => 63, "label" => "Kenyan Shilling", "abrv" => "KES"],
        ["value" => 64, "label" => "Kuwaiti Dinar", "abrv" => "KWD"],
        ["value" => 65, "label" => "Kyrgyzstani Som", "abrv" => "KGS"],
        ["value" => 66, "label" => "Lao Kip", "abrv" => "LAK"],
        ["value" => 67, "label" => "Latvian Lats", "abrv" => "LVL"],
        ["value" => 68, "label" => "Lebanese Pound", "abrv" => "LBP"],
        ["value" => 69, "label" => "Lesotho Loti", "abrv" => "LSL"],
        ["value" => 70, "label" => "Liberian Dollar", "abrv" => "LRD"],
        ["value" => 71, "label" => "Libyan Dinar", "abrv" => "LYD"],
        ["value" => 72, "label" => "Lithuanian Litas", "abrv" => "LTL"],
        ["value" => 73, "label" => "Macanese Pataca", "abrv" => "MOP"],
        ["value" => 74, "label" => "Malagasy Ariary", "abrv" => "MGA"],
        ["value" => 75, "label" => "Malawian Kwacha", "abrv" => "MWK"],
        ["value" => 76, "label" => "Malaysian Ringgit", "abrv" => "MYR"],
        ["value" => 77, "label" => "Maldivian Rufiyaa", "abrv" => "MVR"],
        ["value" => 78, "label" => "Mauritian Rupee", "abrv" => "MUR"],
        ["value" => 79, "label" => "Mexican Peso", "abrv" => "MXN"],
        ["value" => 80, "label" => "Moroccan Dirham", "abrv" => "MAD"],
        ["value" => 81, "label" => "Mozambican Metical", "abrv" => "MZN"],
        ["value" => 82, "label" => "Myanmar Kyat", "abrv" => "MMK"],
        ["value" => 83, "label" => "Namibian Dollar", "abrv" => "NAD"],
        ["value" => 84, "label" => "Nepalese Rupee", "abrv" => "NPR"],
        ["value" => 85, "label" => "New Taiwan Dollar", "abrv" => "TWD"],
        ["value" => 86, "label" => "New Zealand Dollar", "abrv" => "NZD"],
        ["value" => 87, "label" => "Nicaraguan Córdoba", "abrv" => "NIO"],
        ["value" => 88, "label" => "Nigerian Naira", "abrv" => "NGN"],
        ["value" => 89, "label" => "North Korean Won", "abrv" => "KPW"],
        ["value" => 90, "label" => "Norwegian Krone", "abrv" => "NOK"],
        ["value" => 91, "label" => "Omani Rial", "abrv" => "OMR"],
        ["value" => 92, "label" => "Pakistani Rupee", "abrv" => "PKR"],
        ["value" => 93, "label" => "Panamanian Balboa", "abrv" => "PAB"],
        ["value" => 94, "label" => "Papua New Guinean Kina", "abrv" => "PGK"],
        ["value" => 95, "label" => "Paraguayan Guarani", "abrv" => "PYG"],
        ["value" => 96, "label" => "Peruvian Sol", "abrv" => "PEN"],
        ["value" => 97, "label" => "Philippine Peso", "abrv" => "PHP"],
        ["value" => 98, "label" => "Polish Zloty", "abrv" => "PLN"],
        ["value" => 99, "label" => "Qatari Riyal", "abrv" => "QAR"],
        ["value" => 100, "label" => "Romanian Leu", "abrv" => "RON"],
        ["value" => 101, "label" => "Russian Ruble", "abrv" => "RUB"],
        ["value" => 102, "label" => "Rwandan Franc", "abrv" => "RWF"],
        ["value" => 103, "label" => "Saint Helena Pound", "abrv" => "SHP"],
        ["value" => 104, "label" => "Samoan Tala", "abrv" => "WST"],
        ["value" => 105, "label" => "Saudi Riyal", "abrv" => "SAR"],
        ["value" => 106, "label" => "Serbian Dinar", "abrv" => "RSD"],
        ["value" => 107, "label" => "Seychellois Rupee", "abrv" => "SCR"],
        ["value" => 108, "label" => "Sierra Leonean Leone", "abrv" => "SLL"],
        ["value" => 109, "label" => "Singapore Dollar", "abrv" => "SGD"],
        ["value" => 110, "label" => "Solomon Islands Dollar", "abrv" => "SBD"],
        ["value" => 111, "label" => "Somali Shilling", "abrv" => "SOS"],
        ["value" => 112, "label" => "South African Rand", "abrv" => "ZAR"],
        ["value" => 113, "label" => "South Korean Won", "abrv" => "KRW"],
        ["value" => 114, "label" => "South Sudanese Pound", "abrv" => "SSP"],
        ["value" => 115, "label" => "Sri Lankan Rupee", "abrv" => "LKR"],
        ["value" => 116, "label" => "Sudanese Pound", "abrv" => "SDG"],
        ["value" => 117, "label" => "Surilabelse Dollar", "abrv" => "SRD"],
        ["value" => 118, "label" => "Swazi Lilangeni", "abrv" => "SZL"],
        ["value" => 119, "label" => "Swedish Krona", "abrv" => "SEK"],
        ["value" => 120, "label" => "Swiss Franc", "abrv" => "CHF"],
        ["value" => 121, "label" => "Syrian Pound", "abrv" => "SYP"],
        ["value" => 122, "label" => "Tajikistani Somoni", "abrv" => "TJS"],
        ["value" => 123, "label" => "Tanzanian Shilling", "abrv" => "TZS"],
        ["value" => 124, "label" => "Thai Baht", "abrv" => "THB"],
        ["value" => 125, "label" => "Tongan Paʻanga", "abrv" => "TOP"],
        ["value" => 126, "label" => "Trinvaluead and Tobago Dollar", "abrv" => "TTD"],
        ["value" => 127, "label" => "Tunisian Dinar", "abrv" => "TND"],
        ["value" => 128, "label" => "Turkish Lira", "abrv" => "TRY"],
        ["value" => 129, "label" => "Turkmenistani Manat", "abrv" => "TMT"],
        ["value" => 130, "label" => "Ugandan Shilling", "abrv" => "UGX"],
        ["value" => 131, "label" => "Ukrainian Hryvnia", "abrv" => "UAH"],
        ["value" => 132, "label" => "United Arab Emirates Dirham", "abrv" => "AED"],
        ["value" => 133, "label" => "United States Dollar", "abrv" => "USD"],
        ["value" => 134, "label" => "Uruguayan Peso", "abrv" => "UYU"],
        ["value" => 135, "label" => "Uzbekistani Som", "abrv" => "UZS"],
        ["value" => 136, "label" => "Vanuatu Vatu", "abrv" => "VUV"],
        ["value" => 137, "label" => "Venezuelan Bolívar", "abrv" => "VES"],
        ["value" => 138, "label" => "Vietlabelse Đồng", "abrv" => "VND"],
        ["value" => 139, "label" => "Yemeni Rial", "abrv" => "YER"],
        ["value" => 140, "label" => "Zambian Kwacha", "abrv" => "ZMW"],
        ["value" => 141, "label" => "Zimbabwean Dollar", "abrv" => "ZWL"],
    ],
];
